#!/usr/bin/env python3
"""Deep dive for static108 CBO-vs-BO segment analysis.

Input is the analysis directory generated by analyze_static108_core_v15.py.
It expects a pairs CSV such as cbo_vs_bo_pairs.csv.
"""

from __future__ import annotations

import argparse
from pathlib import Path

import numpy as np
import pandas as pd


SEGMENT_ORDER = {
    "001-050": 1,
    "051-100": 2,
    "101-200": 3,
    "201-300": 4,
    "301-400": 5,
    "401-500": 6,
    "451-500": 7,
    "all500": 8,
}

FOCUS_METRICS = ("eval_cost_mean", "normalized_tradeoff_mean")


def finite_mean(values) -> float:
    arr = np.asarray(values, dtype=float)
    arr = arr[np.isfinite(arr)]
    return float(arr.mean()) if arr.size else np.nan


def load_pairs(path: Path) -> pd.DataFrame:
    if path.is_dir():
        candidates = [
            path / "cbo_vs_bo_pairs.csv",
            path / "cbo_vs_bo_pairs.csv",
            path / "cbo_vs_bo_by_scene_seed.csv",
        ]
        for cand in candidates:
            if cand.exists():
                path = cand
                break
        else:
            files = sorted(path.glob("*pairs.csv"))
            if not files:
                raise SystemExit(f"No *pairs.csv found in {path}")
            path = files[0]
    df = pd.read_csv(path, low_memory=False)
    if "scenario" not in df.columns or "segment" not in df.columns:
        raise SystemExit(f"Pairs file does not look valid: {path}")
    return df


def scene_segment_table(pairs: pd.DataFrame) -> pd.DataFrame:
    rows = []
    for (scenario, segment), group in pairs.groupby(["scenario", "segment"], sort=False):
        row = {
            "scenario": scenario,
            "segment": segment,
            "segment_order": SEGMENT_ORDER.get(str(segment), 999),
            "seed_count": int(group["seed"].nunique()) if "seed" in group.columns else int(len(group)),
        }
        if "/" in str(scenario):
            row["lambda_tag"], row["scene"] = str(scenario).split("/", 1)
        else:
            row["lambda_tag"], row["scene"] = "", str(scenario)
        for metric in FOCUS_METRICS:
            delta_col = f"delta_{metric}"
            rel_col = f"relative_pct_{metric}"
            win_col = f"compare_win_{metric}"
            if delta_col not in group.columns:
                continue
            delta = pd.to_numeric(group[delta_col], errors="coerce")
            rel = pd.to_numeric(group[rel_col], errors="coerce") if rel_col in group.columns else pd.Series(np.nan, index=group.index)
            row[f"{metric}_mean_delta"] = finite_mean(delta)
            row[f"{metric}_mean_relative_pct"] = finite_mean(rel)
            row[f"{metric}_wins"] = int(pd.to_numeric(group.get(win_col, False), errors="coerce").fillna(0).sum()) if win_col in group.columns else int((delta < 0).sum())
        rows.append(row)
    out = pd.DataFrame(rows)
    return out.sort_values(["segment_order", "scenario"]).reset_index(drop=True)


def convergence_table(scene_segments: pd.DataFrame) -> pd.DataFrame:
    rows = []
    ordered_segments = [s for s, _ in sorted(SEGMENT_ORDER.items(), key=lambda kv: kv[1]) if s != "all500"]
    for scenario, group in scene_segments.groupby("scenario", sort=False):
        row = {"scenario": scenario}
        if "/" in str(scenario):
            row["lambda_tag"], row["scene"] = str(scenario).split("/", 1)
        else:
            row["lambda_tag"], row["scene"] = "", str(scenario)
        group = group.set_index("segment")
        for metric in FOCUS_METRICS:
            deltas = []
            first_win = None
            first_sustained = None
            for seg in ordered_segments:
                val = group.loc[seg, f"{metric}_mean_delta"] if seg in group.index else np.nan
                deltas.append((seg, val))
                if first_win is None and np.isfinite(val) and val < 0:
                    first_win = seg
            for i, (seg, val) in enumerate(deltas):
                rest = [v for _, v in deltas[i:] if np.isfinite(v)]
                if rest and all(v < 0 for v in rest):
                    first_sustained = seg
                    break
            early = group.loc["001-050", f"{metric}_mean_delta"] if "001-050" in group.index else np.nan
            late = group.loc["451-500", f"{metric}_mean_delta"] if "451-500" in group.index else np.nan
            all500 = group.loc["all500", f"{metric}_mean_delta"] if "all500" in group.index else np.nan
            row[f"{metric}_first_win_segment"] = first_win or ""
            row[f"{metric}_first_sustained_win_segment"] = first_sustained or ""
            row[f"{metric}_early_delta"] = early
            row[f"{metric}_late_delta"] = late
            row[f"{metric}_all500_delta"] = all500
            row[f"{metric}_late_minus_early_delta"] = late - early if np.isfinite(late) and np.isfinite(early) else np.nan
        rows.append(row)
    return pd.DataFrame(rows)


def segment_summary(scene_segments: pd.DataFrame) -> pd.DataFrame:
    rows = []
    for segment, group in scene_segments.groupby("segment", sort=False):
        row_base = {"segment": segment, "segment_order": SEGMENT_ORDER.get(str(segment), 999), "scene_count": int(group["scenario"].nunique())}
        for metric in FOCUS_METRICS:
            delta_col = f"{metric}_mean_delta"
            rel_col = f"{metric}_mean_relative_pct"
            if delta_col not in group.columns:
                continue
            delta = pd.to_numeric(group[delta_col], errors="coerce")
            rel = pd.to_numeric(group[rel_col], errors="coerce")
            rows.append({
                **row_base,
                "metric": metric,
                "scene_wins": int((delta < 0).sum()),
                "scene_losses": int((delta > 0).sum()),
                "mean_delta": finite_mean(delta),
                "mean_relative_pct": finite_mean(rel),
                "worst_scene": group.loc[delta.idxmax(), "scenario"] if len(delta.dropna()) else "",
                "worst_delta": float(delta.max()) if len(delta.dropna()) else np.nan,
                "best_scene": group.loc[delta.idxmin(), "scenario"] if len(delta.dropna()) else "",
                "best_delta": float(delta.min()) if len(delta.dropna()) else np.nan,
            })
    return pd.DataFrame(rows).sort_values(["segment_order", "metric"]).reset_index(drop=True)


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("analysis_dir_or_pairs_csv", type=Path)
    parser.add_argument("--output", type=Path, default=None)
    parser.add_argument("--topn", type=int, default=20)
    args = parser.parse_args()

    pairs = load_pairs(args.analysis_dir_or_pairs_csv.resolve())
    output = args.output or (
        args.analysis_dir_or_pairs_csv.resolve()
        if args.analysis_dir_or_pairs_csv.resolve().is_dir()
        else args.analysis_dir_or_pairs_csv.resolve().parent
    )
    output.mkdir(parents=True, exist_ok=True)

    scene_segments = scene_segment_table(pairs)
    conv = convergence_table(scene_segments)
    summary = segment_summary(scene_segments)

    scene_segments.to_csv(output / "deep_scene_segment_metrics.csv", index=False, encoding="utf-8-sig")
    conv.to_csv(output / "deep_scene_convergence.csv", index=False, encoding="utf-8-sig")
    summary.to_csv(output / "deep_segment_summary.csv", index=False, encoding="utf-8-sig")

    print(f"output: {output}")
    print("\n=== Segment summary ===")
    print(summary[summary["metric"].isin(FOCUS_METRICS)].to_string(index=False))

    for seg in ("001-050", "451-500", "all500"):
        print(f"\n=== Worst {args.topn} scenes: {seg} eval_cost_mean ===")
        subset = scene_segments[scene_segments["segment"] == seg].copy()
        subset = subset.sort_values("eval_cost_mean_mean_delta", ascending=False).head(args.topn)
        cols = ["scenario", "eval_cost_mean_mean_delta", "eval_cost_mean_mean_relative_pct", "normalized_tradeoff_mean_mean_delta", "normalized_tradeoff_mean_mean_relative_pct"]
        print(subset[cols].to_string(index=False))

    print("\n=== Earliest sustained wins by Eval_Cost ===")
    tmp = conv[conv["eval_cost_mean_first_sustained_win_segment"].astype(str) != ""].copy()
    tmp["order"] = tmp["eval_cost_mean_first_sustained_win_segment"].map(SEGMENT_ORDER)
    print(tmp.sort_values(["order", "eval_cost_mean_late_delta"]).head(args.topn)[[
        "scenario", "eval_cost_mean_first_sustained_win_segment",
        "eval_cost_mean_early_delta", "eval_cost_mean_late_delta", "eval_cost_mean_all500_delta"
    ]].to_string(index=False))


if __name__ == "__main__":
    main()
